### ISSUE TITLE
Project Filters or Status type

### ISSUE THREAD

**Issue by JacquiSwartz** [datala/dot-planner#138]
Allow user to filter by project type (ie if user would like to only see Bike projects, one can select 'Funded>Bike' or 'Funded>First/Last Mile'.  Also need filter for projects that are re-occurring such as CicLAvia (routes will generally be the same but dates are only 'active' or 'funded' for time of event) or in cases where the project status has changed and is on hold. Project Managers will want to place on 'HOLD' or 'HIDE'.

**Comment by bryce-richards** [comment]
Added Funded/Unfunded buttons and additional functionality for dropdown checkbox list filtering.
